#!/usr/bin/perl

use strict;
use warnings;

use File::Basename;

my $dirname = dirname(__FILE__);
my $configure = "$dirname/configure.ac";

unless (-e "$configure") {
  $configure = "$dirname/../configure.ac";
}

open(my $CONF, "<", "$configure")
  or die "Failed to get Stow version.\nSearch path: '$configure'\nUnable to find 'configure.ac' file: '$!'";

while (my $line = <$CONF>) {
  if ($line =~ /^AC_INIT\(\[stow\], \[(.+?)\]/) {
    print "$1\n";
    exit 0;
  }
}

exit 1;
