name: 'Build and Test'

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - "**"
  pull_request:
    branches: [main, master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-test-linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      DEBIAN_FRONTEND: noninteractive

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Dependencies
        working-directory: ${{ github.workspace }}
        run: |
          sudo apt-get update
          sudo apt-get -y install --no-install-recommends \
            autoconf \
            bzip2 \
            cpanminus \
            gawk \
            curl \
            libssl-dev \
            make \
            patch

      - name: Perl Dependencies
        working-directory: ${{ github.workspace }}
        run: |
          sudo cpan -i -T YAML Test::Output Test::More CPAN::DistnameInfo

      - name: Build
        working-directory: ${{ github.workspace }}
        run: |
          autoreconf -iv
          eval `perl -V:siteprefix`
          ./configure --prefix=$siteprefix
          make bin/stow bin/chkstow lib/Stow.pm lib/Stow/Util.pm
          perl Build.PL
          perl Build test
          sudo perl Build install

  build-test-msys2:
    needs: build-test-linux
    runs-on: windows-latest
    env:
      # https://cygwin.com/cygwin-ug-net/using-cygwinenv.html
      MSYS: "winsymlinks:native"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64

          # Minimal here so that we use the MSYS perl and not the version
          # already installed (if there is one)
          path-type: minimal

          update: false
          install: >-
            base-devel
            git
            mingw-w64-x86_64-gcc
            make
            autoconf
            automake1.16
            automake-wrapper
            libtool
            perl

      - name: MSYS2 Make Stow
        shell: msys2 {0}
        run: |
          cd $(cygpath '${{ github.workspace }}')
          ./.github/make-stow.sh

      - name: MSYS2 Test
        shell: msys2 {0}
        run: |
          cd $(cygpath '${{ github.workspace }}')
          prove -I t/ -I bin/ -I lib/

  build-test-windows:
    needs: build-test-linux
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.32'
          distribution: strawberry

      - name: Perl Dependencies
        working-directory: ${{ github.workspace }}
        run: |
          cpan -i -T YAML Test::Output CPAN::DistnameInfo

      - name: Build
        working-directory: ${{ github.workspace }}
        run: |
          call .github\make-stow.bat
          perl Build.PL
          call Build.bat installdeps
          call Build.bat test

      # This will fail until symlinks are supported
      # - name: Test
      #   working-directory: ${{ github.workspace }}
      #   run: |
      #     prove -I t/ -I bin/ -I lib/
