name: stow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - "**"
  pull_request:
    branches: [main, master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ubuntu:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      HOME: /root
      PERLBREW_ROOT: /usr/local/perlbrew
      PERLBREW_HOME: /root/.perlbrew
      PERLBREW_PATH: /usr/local/perlbrew/bin

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Dependencies
        working-directory: ${{ github.workspace }}
        run: |
          DEBIAN_FRONTEND=noninteractive apt-get update -qq
          DEBIAN_FRONTEND=noninteractive apt-get install -y -q \
            autoconf \
            bzip2 \
            cpanminus \
            gawk \
            git \
            libssl-dev \
            make \
            patch \
            perlbrew \
            texinfo \
            texlive \
            texi2html

      - name: Setup perlbrew
        working-directory: ${{ github.workspace }}
        run: |
          mkdir -p /usr/local/perlbrew /root
          perlbrew init
          perlbrew install-cpanm
          perlbrew install-patchperl
          perlbrew install-multiple -j 4 --notest \
            perl-5.22.2 \
            perl-5.20.3

      - name: Build
        working-directory: ${{ github.workspace }}
        run: |
          eval `perl -V:siteprefix`
          ./configure --prefix=$siteprefix && make
          perl Build.PL

      - name: Bootstrap Perls
        working-directory: ${{ github.workspace }}
        run: ./docker/bootstrap-perls.sh

      - name: Stow Tests
        working-directory: ${{ github.workspace }}
        run: ./docker/run-stow-tests.sh

  windows-msys2:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            base-devel
            git
            mingw-w64-x86_64-gcc
            make
            autoconf
            automake1.16
            automake-wrapper
            libtool
            perl
            texinfo
            texinfo-tex
            mingw-w64-x86_64-texlive-core
            mingw-w64-x86_64-texlive-bin
            mingw-w64-x86_64-texlive-plain-generic

      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build and Test
        run: |
          eval `perl -V:siteprefix`
          ./configure --prefix=$siteprefix && make
          perl Build.PL
          perl Build
          perl Build test
