name: 'Nightly'

on:
  # Run at 2 AM UTC every day
  schedule:
    - cron: '0 2 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  perl_test_matrix:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        perl:
          - '5.32'
          - '5.14'

        include:
          - platform: ubuntu-latest
            perl: '5.34'

    name: ${{ matrix.platform }} Perl v${{ matrix.perl }}
    runs-on: ${{ matrix.platform }}
    if: always()

    env:
      DEBIAN_FRONTEND: noninteractive

      # Define variants by platform
      shell: ${{ startsWith(matrix.platform, 'windows') && 'cmd' || 'bash' }}
      script_extension: ${{ startsWith(matrix.platform, 'windows') && '.bat' || '.sh' }}
      script_prefix: ${{ startsWith(matrix.platform, 'windows') && 'cmd /c tools\\' || 'bash tools/' }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Perl ${{ matrix.perl }}
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}

          # Only applies to Windows and uses fallback for other platforms
          distribution: strawberry

      - name: Install Dependencies
        shell: ${{ env.shell }}
        working-directory: ${{ github.workspace }}
        run: |
          ${{ env.script_prefix }}install-dependencies${{ env.script_extension }}

      - name: Make Stow
        shell: ${{ env.shell }}
        working-directory: ${{ github.workspace }}
        run: |
          ${{ env.script_prefix }}make-stow${{ env.script_extension }}

      - name: Run Tests
        shell: ${{ env.shell }}
        working-directory: ${{ github.workspace }}
        run: |
          ${{ env.script_prefix }}run-tests${{ env.script_extension }}

  docker_build:
    name: Docker Perl Tests

    # Skip Docker build if the test matrix fails as this will take a long time and
    # does essentially the same as above but with 'perlbrew'
    needs: perl_test_matrix

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker build image
        working-directory: ${{ github.workspace }}
        run: |
          bash ./docker/docker-build.sh

      - name: Docker test
        working-directory: ${{ github.workspace }}
        run: |
          bash ./docker/docker-test.sh
