name: 'Nightly'

on:
  # Run at 2 AM UTC every day
  schedule:
    - cron: '0 2 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker_build:
    name: Docker - Perl Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker build image
        working-directory: ${{ github.workspace }}
        run: |
          bash ./docker/docker-build.sh

      - name: Docker test
        working-directory: ${{ github.workspace }}
        run: |
          bash ./docker/docker-test.sh


  perl_test_matrix:
    name: Validate Perl Versions

    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        perl:
          - '5.34'
          - '5.14'

        install:
          - bash tools/install-dependencies.sh
        make:
          - bash tools/make-stow.sh
        test:
          - bash tools/run-tests.sh

        include:
          - platform: windows-latest
            install: cmd /c tools\install-dependencies.bat
            make: cmd /c tools\make-stow.bat
            test: cmd /c tools\run-tests.bat

    runs-on: ${{ matrix.platform }}
    if: always()

    env:
      DEBIAN_FRONTEND: noninteractive

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Perl ${{ matrix.perl }}
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}

          # Only applies to Windows and uses fallback for other platforms
          distribution: strawberry

      - name: Install Dependencies
        working-directory: ${{ github.workspace }}
        run: |
          ${{ matrix.install }}

      - name: Make Stow
        working-directory: ${{ github.workspace }}
        run: |
          ${{ matrix.make }}

      - name: Run Tests
        working-directory: ${{ github.workspace }}
        run: |
          ${{ matrix.test }}
